import Head from 'next/head'
// import Image from 'next/image'
import { useState } from 'react'
import { useEffect } from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [count, setCount] = useState(0);

  useEffect ( () => {
    document.title = `Total : ${count}`;
  },[count]);

  const handleClickNeg = () => {
    setCount(count-1);
  }
  const handleClick1 = () => {
    setCount(count+1);
  }
  const handleClick3 = () => {
    setCount(count+3);
  }
  const handleClick5 = () => {
    setCount(count+5);
  }
  const zero = () => {
    setCount(0);
  }
 
  return (
    <>
      <Head>
        {/* <title>Create Next App</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p className={styles.heading}>
            Target Counter
          </p>
        </div>

      <div className={styles.congo}>
      <div>
          {count <0 ? (
            <p>Bhaisahab ye kis line m aa gye hain ap</p>
          ):
          (null)
          }
        </div>
        <div>
          {count >=50 && count < 100 ? (
            <p>Take some break,Snack Time🍌🍌🍌</p>
          ):
          (null)
          }
        </div>

        <div>
          {count >= 100 && count < 180 ? (
            <p>You can do it, push harder</p>
          ):
          (null)
          }
        </div>

        <div >
          {count >= 180 && count < 240 ? (
            <p>Just a few miles away🛣️🛣️</p>
          ):
          (null)
          }
        </div>

        <div>
          {count >= 240 && count < 275 ? (
            <p>Target Completed, Hurray🎉🥳🎉</p>
          ):
          (null)
          }
        </div>

        <div>
          {count >= 275 ? (
           <p className={styles.para}>Bass kar bhai, company ka share leke hi manega kya</p>
          ):
          (null)
          }
        </div>
        </div>

        <div className={styles.center}>
          <b className={styles.b}>{count}</b>
        </div>
        <div>
        <button className={styles.buttonNeg} onClick={handleClickNeg} >-1</button>
          <button className={styles.button1} onClick={handleClick1} >+1</button>
          <button className={styles.button3} onClick={handleClick3} >+3</button>
          <button className={styles.button5} onClick={handleClick5} >+5</button>
        </div>
        
        <button className={styles.button0} onClick={zero} >Reset</button>

      </main>
    </>
  )
}
